databases:
  - name: budget
    databaseName: budget_mxu6
    user: budget_mxu6_user

services:
  - type: web
    name: budgetApp
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: budget
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false